# Generated by Django 6.0.4 on 2026-04-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefactura',
            options={'verbose_name': 'Detalle de Factura', 'verbose_name_plural': 'Detalles de Factura'},
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto_nombre',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tipo_empaque',
            field=models.CharField(default='Normal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=20),
        ),
    ]
